cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

nike_shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name='order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory, name='order_history'),
    path('<int:order_id>/', views.viewOrder, name='order_detail'),
]

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<uuid:category_id>/', views.allProdCat, name='products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', views.prod_detail, name='prod_detail'),
]

shop/models.py
import uuid
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)

    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
        
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:prod_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def allProdCat(request, category_id=None):
    c_page = None
    products_list = None
    if category_id !=None:
        c_page = get_object_or_404(Category, id=category_id)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    """Pagination Code"""
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)
  

    return render(request, 'shop/category.html', {'category':c_page,'products':products})
   
def prod_detail(request, category_id, product_id):
    try:
        product = Product.objects.get(category_id=category_id, id=product_id)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product':product})

   

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	
		{% include 'navbar.html' %}
		<div class="container">
		{% include 'header.html' %}
		
		{% block content %}
		{% endblock %}
	</div>
	
	
		{% include 'footer.html' %}



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom bg-light py-5">
	<p class="text-center mx-auto">&copy; Nike. All Rights Reserved.</p>
</div>

shop/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;">
        <!--<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'images/jumpmanlogo.png' %}" alt="Online Nike Store"></div></a> -->
    </div>
</header>

shop/templates/navbar.html
{% load static %}
<nav style="padding-bottom: 5rem;" class="navbar navbar-expand-lg navbar-light bg-white mb-5">
    
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shoes
        </a>
        <div class="dropdown-menu bg-light" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat'%}">All Shoes</a>
            <div class="dropdown-divider"></div>
              {% for cat in links %}
              <a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a>
              {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
      {% endif%}
      </li>
        <a style="left: 46.5vw; top: 10px; position:absolute"  class="navbar-brand" href="{% url 'shop:allProdCat' %}"><img style="height:29px;" src="{% static 'images/jumpmanlogo.png' %}" alt="Online Nike Store">
        
        </ul></div></a>
    
     
     
      
    </div>
      
   
   <ul class="navbar-nav">
    <form action="{% url 'search_app:searchResult' %}" method="get" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 text-light rounded-pill" type="search" placeholder="Search" aria-label="Search" name="q">
    </form>
    {% if user.is_authenticated %}
    <li class="nav-item text-secondary">
      Welcome, <a class="nav-link" href="#" class="dropdown-toggle" data-toggle="dropdown" 
      aria-haspopup="true" aria-expanded="false">{{ user.username }} 
      <i class="fas fa-user-circle"></i></a>
      <div class="dropdown-menu dropdown-menu-right">
        <a class="nav-link" href="{% url 'order:order_history' %}" class='dropdown-item'>Order History</a>
      </div>
    </li>
    <li class="nav-item text-secondary">
      <a class="nav-link" href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
    </li>
    {% else %}
    <li class="nav-item text-secondary">
      <a class="nav-link" href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
    </li>
    {% endif %}
  </ul>
</nav>